# Numerical Analysis with Python Programming

Created by Ted Yap on November 13, 2018

In [94]:
import math
import numpy

# Solutions of Equations in One Variable

## Bisection Method

To find a solution to $f(x) = 0$ given the continuous function $f$ on the interval $[a,b]$, where $f(a)$ and $f(b)$ have opposite signs

In [193]:
def Bisection(a,b,delta):
    """
    INPUT:
        a, b - endpoints
        delta - tolerance
    OUTPUT:
        approximate solution p at iteration n
    """
    max_iter = 1 + math.floor((math.log(b-a)-math.log(delta))/math.log(2))
    k = 1
    dx = b-a
    print("a = ", a)
    print("b = ", b)
    if f(a)*f(b) > 0:
        print("No root found.")
    else:
        while ((b-a)/2.0 > delta) and (k < max_iter):
            midpoint = (a+b)/2.0
            print("k = ",k,"\t c = ", midpoint,"\t\t |dc| <= ",dx)
            if f(midpoint) == 0:
                return(midpoint)
            elif f(a)*f(midpoint) < 0:
                b = midpoint
            else:
                a = midpoint
            dx = b-a
            k += 1
        print("k = ",k,"\t c = ", midpoint,"\t\t |dc| <= ",dx)
        print("solution: ",midpoint)
        print("iteration executed: ",k)

In [8]:
f = lambda x: x**3-7*x**2+14*x-6

In [9]:
Bisection(0,1,10**-2)

a =  0
b =  1
k =  1 	 c =  0.5 		 |dc| <=  1
k =  2 	 c =  0.75 		 |dc| <=  0.5
k =  3 	 c =  0.625 		 |dc| <=  0.25
k =  4 	 c =  0.5625 		 |dc| <=  0.125
k =  5 	 c =  0.59375 		 |dc| <=  0.0625
k =  6 	 c =  0.578125 		 |dc| <=  0.03125
k =  7 	 c =  0.578125 		 |dc| <=  0.015625
solution:  0.578125
iteration executed:  7


## Fixed-Point Iteration

To find a solution $p=g(p)$ given an initial approximation $p_0$

In [76]:
def Fixed_Point(p_0,delta,n):
    """
    INPUT:
        p_0 - initial approximation
        delta - tolerance
        n - maximum number of iterations
    OUTPUT:
        approximate solution p at iteration n
    """
    i = 1
    print("n   p")
    print("{:<3} {:<10.9f}".format(0,p_0))
    while i <= n:
        p = g(p_0)
        print("{:<3} {:<10.9f}".format(i,p))
        if abs(p - p_0) < delta:
            print("{:<3} {:<10.9f}".format(i+1,p))
            return
        i += 1
        p_0 = p
    print("Method failed after {} iterations".format(n))

In [77]:
g = lambda x: ((10-x**3)**0.5)/2

In [78]:
Fixed_Point(1.5,0.01,30)

n   p
0   1.500000000
1   1.286953768
2   1.402540804
3   1.345458374
4   1.375170253
5   1.360094193
6   1.367846968
7   1.367846968


## Newton's Method

To find a solution to $f(x) = 0$ given an initial approximation $p_0$

In [ ]:
def Newton(p_0,delta,n):
    
    i = 1
    while i <= n:
        p = p_0 - f(p_0)/
        if abs(p - p_0) < delta:
            print
            return
        i += 1
        p_0 = p
    print("Method failed after {} iterations".format(n))

## Secant Method

To find a solution to $f(x) = 0$ given an initial approximation $p_0$ when $f'(x)$ is hard to find. An approximation to Newton's method.

In [192]:
def Secant_Method(p0,p1,n):
    """
    INPUT:
        p0, p1 - initial approximations
        n - maximum number of iterations
    OUTPUT:
        approximate solution p at iteration n
    """
    k = 1
    q0 = f(p0)
    q1 = f(p1)
    print("p at iteration", 0, "is", p0)
    print("p at iteration", 1, "is", p1)
    for i in range(n):
        p = p1 - (q1*(p1-p0))/(q1-q0)
        k += 1
        print("p at iteration", k, "is", p)
        p0 = p1
        q0 = q1
        p1 = p
        q1 = f(p)

In [82]:
f = lambda x: x**2-6

In [83]:
Secant_Method(3,2,5)

p at iteration 0 is 3
p at iteration 1 is 2
p at iteration 2 is 2.4
p at iteration 3 is 2.4545454545454546
p at iteration 4 is 2.449438202247191
p at iteration 5 is 2.44948968964799
p at iteration 6 is 2.449489742783737


## False Position Method

To find a solution to $f(x) = 0$ given the continuous function $f$ on the interval $[p_0,p_1]$ where $f(p_0)$ and $f(p_1)$ have opposite signs

In [191]:
def False_Position(p0,p1,n):
    """
    INPUT:
        p0, p1 - initial approximations
        n - maximum number of iterations
    OUTPUT:
        approximate solution p at iteration n
    """
    k = 1
    q0 = f(p0)
    q1 = f(p1)
    print("p at iteration", 0, "is", p0)
    print("p at iteration", 1, "is", p1)
    for i in range(n):
        p = p1 - (q1*(p1-p0))/(q1-q0)
        k += 1
        print("p at iteration", k, "is", p)
        q = f(p)
        if q*q1 < 0:
            p0 = p1
            q0 = q1
        p1 = p
        q1 = f(p)

In [84]:
False_Position(3,2,5)

p at iteration 0 is 3
p at iteration 1 is 2
p at iteration 2 is 2.4
p at iteration 3 is 2.444444444444444
p at iteration 4 is 2.4489795918367347
p at iteration 5 is 2.449438202247191
p at iteration 6 is 2.4494845360824744


## Aitken's Method

A technique that can be used to accelerate the convergence of a sequence that is linearly convergent

In [85]:
def Aitken(p0,n):
    """
    INPUT:
        p0 - initial approximation 
        n - maximum number of iterations
    OUTPUT:
        approximate solution p at iteration n
    """
    k = 0
    for i in range(n):
        p1 = f(p0)
        p2 = f(p1)
        p = p0 - ((p1 - p0)**2)/(p2 - 2*p1 + p0)
        print("p at iteration", k, "is", p)
        k += 1
        p0 = p1

In [86]:
f = lambda x: (2 - math.exp(x) + x**2)/3

In [87]:
Aitken(0.5,5)

p at iteration 0 is 0.2586844275657909
p at iteration 1 is 0.2576132107157495
p at iteration 2 is 0.25753583232666766
p at iteration 3 is 0.2575306600010322
p at iteration 4 is 0.25753031065960186


## Steffensen's Method

A technique used to accelerate the convergence to quadratic by appying a modification of Aitken's method.

In [88]:
def Steffensen(p0,n):
    """
    INPUT:
        p0 - initial approximation 
        n - maximum number of iterations
    OUTPUT:
        approximate solution p at iteration n
    """
    k = 0
    for i in range(n):
        p1 = f(p0)
        p2 = f(p1)
        p = p0 - ((p1 - p0)**2)/(p2 - 2*p1 + p0)
        print("p at iteration", k, "is", p)
        k += 1
        p0 = p

In [91]:
f = lambda x: math.cos(x-1)

In [92]:
Steffensen(2,4)

p at iteration 0 is 0.8264273956775894
p at iteration 1 is 1.0014354914634551
p at iteration 2 is 0.999999999261024
p at iteration 3 is 1.0


# Interpolation and Polynomial Approximation

## Lagrange Polynomial with Neville's Iterated Interpolation

To evaluate the interpolating polynomial $P(x)$ on the $n + 1$ distinct numbers $x_0,...x_n$ at the number $x$ for the function $f$

In [232]:
def Neville(x,xlist):
    """
    INPUT:
        x - value of x to find f(x) at
        xlist - list of x_0,...,x_n
    OUTPUT:
        numpy array -  two-dimensional array of function values.
        The [n,n] value of this array should be the
        most accurate estimate of f(x)
    """
    n = len(xlist)
    q = numpy.zeros(shape=(n,n))
    for r in range(n):
        q[r][0] = f(xlist[r])
    for i in range(1,n):
        for j in range(1,i+1):
            q[i][j] = ((x-xlist[i-j])*(q[i][j-1])-(x-xlist[i])*(q[i-1][j-1]))/(xlist[i]-xlist[i-j])
    print(q)

In [233]:
f = lambda x: math.cos(x)

In [234]:
Neville(0.45,[0,0.6,0.9])

[[1.         0.         0.        ]
 [0.82533561 0.86900171 0.        ]
 [0.62160997 0.92719844 0.89810007]]


In [231]:
#absolute error
abs_error = abs(math.cos(0.45)-0.8981)
abs_error

0.0023471023526768775

## Newtons's Divided-Difference

To obtain the divided-difference coefficients of the interpolatory polynomial $P(x)$ on the $n+1$ distinct numbers $x_0,...x_n$ at the number $x$ for the function $f$

In [237]:
def NewtonDD(xlist,ylist):
    """
    INPUT:
        xlist - list of x_0,...,x_n
        ylist - list of f(x_0),...f(x_n)
    OUTPUT:
        numpy array -  two-dimensional array of divided-difference coefficients.
        F[i,i] = f[x_0,x_1,...,x_i]
    """
    n = len(xlist)
    F = numpy.zeros(shape=(n,n))
    for m in range(n):
        F[m][0] = ylist[m]
    for i in range(1,n):
        for j in range(1,i+1):
            F[i][j] = (F[i][j-1] - F[i-1][j-1]) / (xlist[i] - xlist[i-j])
    print(F)

In [238]:
NewtonDD([1.0,1.3,1.6,1.9,2.2],[0.7651977,0.6200860,0.4554022,0.2818186,0.1103623])

[[ 0.7651977   0.          0.          0.          0.        ]
 [ 0.620086   -0.48370567  0.          0.          0.        ]
 [ 0.4554022  -0.548946   -0.10873389  0.          0.        ]
 [ 0.2818186  -0.578612   -0.04944333  0.0658784   0.        ]
 [ 0.1103623  -0.571521    0.01181833  0.06806852  0.0018251 ]]


## Hermite Interpolation

To obtain the coefficients of the Hermite interpolating polynomial $H(x)$ on the $n+1$ distinct numbers $x_0,...x_n$ at the number $x$ for the function $f$

In [265]:
def Hermite(xlist,ylist,derivativelist):
    """
    INPUT:
        xlist - numbers x_0,...,x_n
        ylist - values f(x_0),...,f(x_n)
        derivativelist - vaues f'(x_0),...,f'(x_n)
    OUTPUT:
        numpy array -  two-dimensional array of the coefficients of the Hermite interpolating polynomial
    """
    numpy.set_printoptions(precision=8,suppress=True)
    n = len(xlist)
    Q = numpy.zeros(shape=(2*n,2*n))
    z = numpy.zeros(shape=2*n+1)
    for i in range(0,n):
        z[2*i] = xlist[i]
        z[2*i+1] = xlist[i]
        Q[2*i][0] = ylist[i]
        Q[2*i+1][0] = ylist[i]
        Q[2*i+1][1] = derivativelist[i]
        if i != 0:
            Q[2*i][1] = (Q[2*i][0]-Q[2*i-1][0]) / (z[2*i]-z[2*i-1])
            
    for i in range(2,2*n):
        for j in range(2,i+1):
            Q[i][j] = (Q[i][j-1]-Q[i-1][j-1]) / (z[i]-z[i-j])
    return Q

In [266]:
Hermite([8.3,8.6],[17.56492,18.50515],[3.116256,3.151762])

array([[17.56492   ,  0.        ,  0.        ,  0.        ],
       [17.56492   ,  3.116256  ,  0.        ,  0.        ],
       [18.50515   ,  3.1341    ,  0.05948   ,  0.        ],
       [18.50515   ,  3.151762  ,  0.05887333, -0.00202222]])

## Natural Cubic Spline

To construct the cubic spline interpolant $S$ for the function $f$, defined at the numbers $x_0 < x_1 < ... < x_n$, satisfying $S''(x_0)=S''(x_n)=0$

In [ ]:
def Cubic_Spline(xlist,ylist):
    """
    INPUT:
        xlist - numbers x_0,...,x_n
        ylist - values f(x_0),...,f(x_n)
    OUTPUT:
        numpy array -  two-dimensional array of the coefficients of the Hermite interpolating polynomial
    """
    n = len(xlist)
    a = numpy.zeros(shape=n)
    h = numpy.zeros(shape=n-1)
    for i in range(n):
        a[i] = ylist[i]
    for i in range(n-1):
        h[i] = xlist[i+1]-x[i]
    for i in range(1,n-1):
        
        

# Numerical Differentiation and Integration

## Richard's Extrapolation

To approximate $f'(x)$ at a particular $x$.

In [181]:
def Richardson(x,n,h):
    """
    INPUT:
    x - value of x to find derivative at
    n - number of levels of extrapolation
    h - initial stepsize

    OUTPUT:
        numpy array -  two-dimensional array of extrapolation values.
        The [n,n] value of this array should be the
        most accurate estimate of f'(x)
    """
    N = numpy.zeros(shape=(n+1,n+1))
    for i in range(n+1):
        N[i,0] = 0.5 * (f(x+h)-f(x-h))/h
        powerOf4 = 1
        for j in range(1,i+1):
            powerOf4 = 4 * powerOf4
            N[i][j] = N[i][j-1] + (N[i][j-1] - N[i-1][j-1] ) / (powerOf4 - 1)
        h = 0.5 * h
    return N

In [182]:
f = lambda x: math.log(x)

In [183]:
Richardson(1.0,3,0.4)

array([[1.05912233, 0.        , 0.        , 0.        ],
       [1.01366277, 0.99850959, 0.        , 0.        ],
       [1.00335348, 0.99991705, 1.00001088, 0.        ],
       [1.00083459, 0.99999495, 1.00000015, 0.99999998]])

## Composite Simpson's Rule

To approximate the integral $I = \int_{a}^{b} f(x) dx$

In [184]:
def Composite_Simpson(a,b,n):
    """
    INPUT:
        endpoints a, b
        even positive integer n
    OUTPUT:
        approximation XI to I 
    """
    h = (b - a)/n
    I_0 = f(a) + f(b)
    I_1 = 0
    I_2 = 0
    for i in range(1,n):
        X = a + i*h
        if i%2 == 0:
            I_2 = I_2 + f(X)
        else:
            I_1 = I_1 + f(X)
    XI = (h/3)*(I_0 + 2*I_2 + 4*I_1)
    return XI

In [185]:
f = lambda x: x*math.log(x)

In [186]:
Composite_Simpson(1,2,4)

0.6363098297969492

## Romberg Integration

To approximate the integral $I = \int_{a}^{b} f(x) dx$, select an integer $n > 0$

In [187]:
def Romberg(a,b,n):
    """
    INPUT:
    endpoints a, b
    integer n
    OUTPUT:
        numpy array -  two-dimensional array of integral values.
        The [n,n] value of this array should be the
        most accurate estimate of I
    """
    h = b - a
    R = numpy.zeros(shape=(n+1,n+1))
    R[0][0] = (h/2)*(f(a)+f(b))
    powerOf2 = 1
    for i in range(1,n+1):
        h = 0.5 * h
        total = 0.0
        powerOf2 = 2 * powerOf2
        for k in range(1,powerOf2,2):
            total = total + f(a+k*h)
        R[i][0] = 0.5 * R[i-1][0] + total * h
        powerOf4 = 1
        for j in range(1,i+1):
            powerOf4 = 4 * powerOf4
            R[i][j] = R[i][j-1] + (R[i][j-1] - R[i-1][j-1]) / (powerOf4 - 1)
    print(R)

In [188]:
f = lambda x: math.sin(x)

In [189]:
Romberg(0,math.pi,3)

[[1.92367069e-16 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.57079633e+00 2.09439510e+00 0.00000000e+00 0.00000000e+00]
 [1.89611890e+00 2.00455975e+00 1.99857073e+00 0.00000000e+00]
 [1.97423160e+00 2.00026917e+00 1.99998313e+00 2.00000555e+00]]


## Simpson's Double Intergral

To approximate the integral $I = \int^{b}_{a} \int^{d(x)}_{c(x)} \ f(x,y) \ dy \ dx$

In [202]:
def Simpson_Double(a,b,m,n):
    """
    INPUT:
        a, b - endpoints
        m, n - even positive integers for the number of intervals
    OUTPUT:
        approximation J to I
    """
    h = (b-a)/n
    J1 = 0
    J2 = 0
    J3 = 0
    for i in range(n+1):
        x = a + i*h
        HX = (d(x)-c(x))/m
        K1 = f(x,c(x)) + f(x,d(x))
        K2 = 0
        K3 = 0
        for j in range(1,m):
            y = c(x) + j*HX
            Q = f(x,y)
            if j%2 == 0:
                K2 = K2 + Q
            else:
                K3 = K3 + Q
        L = (K1 + 2*K2 + 4*K3)*HX/3
        if i == 0 or i == n:
            J1 = J1 + L
        elif i%2 == 0:
            J2 = J2 + L
        else:
            J3 = J3 + L
    J = (h/3)*(J1 + 2*J2 + 4*J3)
    return J

In [205]:
f = lambda x, y: math.exp(y/x)
d = lambda x: x**2
c = lambda x: x**3

In [206]:
Simpson_Double(0.1,0.5,10,10)

0.033305461281902184

# Initial-Value Problems for Ordinary Differential Equations

## Euler's Method

To approximate the solution of the initial-value problem 

$y'=f(t,y), \ a \leq t \leq b, \ y(a)= \alpha,$

at $n + 1$ equally spaced numbers in the interval $[a,b]$

In [178]:
def Euler(a,b,n,alpha):
    """
    INPUT:
        endpoints a, b
        number of intervals n
        initial condition alpha
    
    OUTPUT:
        approximation w to y at n+1 values of t
    """
    h = (b - a)/n
    t = a
    w = alpha
    for i in range(1,n+1):
        w = w + h*f(t,w)
        t = a + i*h
    return [t,w]

In [179]:
f = lambda t,y: y-t**2+1

In [180]:
Euler(0,2,10,0.5)

[2.0, 4.865784504320001]

For Higher-Order Taylor Methods, we will need a way to compute $\ f^{(n - 1)}$ derivatives. However, computation of $\ f^{(n - 1)}$ derivatives is not required in the Runge-Kutta methods

In [270]:
def RungeKuttaMidpoint(a,b,n,alpha):
    """
    INPUT:
        endpoints a, b
        number of intervals n
        initial condition alpha
    
    OUTPUT:
        approximation w to y at n+1 values of t
    """
    h = (b - a)/n
    t = a
    w = alpha
    for i in range(1,n+1):
        w = w + h*f(t + h/2,w + h/2 * f(t,w))
        t = a + i*h
    return [t,w]

In [271]:
f = lambda t,y: t*math.exp(3*t)-2*y

In [272]:
RungeKuttaMidpoint(0,1,2,0)

[1.0, 3.1300023058804816]

In [273]:
def RungeKuttaOrderFour(a,b,n,alpha):
    """
    INPUT:
        endpoints a, b
        number of intervals n
        initial condition alpha
    
    OUTPUT:
        approximation w to y at n+1 values of t
    """
    h = (b - a)/n
    t = a
    w = alpha
    for i in range(1,n+1):
        k1 = h*f(t,w)
        k2 = h*f(t+h/2,w+k1/2)
        k3 = h*f(t+h/2,w+k2/2)
        k4 = h*f(t+h,w+k3)
        w = w + (k1 + 2*k2 + 2*k3 + k4)/6
        t = a + i*h
    return [t,w]

In [274]:
RungeKuttaOrderFour(0,1,2,0)

[1.0, 3.3143117774778457]